# Generated by Django 5.2.16 on 2026-09-03 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_loanevaluation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanevaluation',
            name='status',
            field=models.CharField(choices=[('unevaluated', 'Unevaluated'), ('accept', 'Accepted'), ('interview', 'Interview'), ('reject', 'Rejected')], default='unevaluated', max_length=11),
        ),
    ]
